### ISSUE TITLE
go test fails

### ISSUE THREAD

**Issue by coderbyheart** [PascalPickel/NAT-TestServer#1]
```
➜ go test
# _/home/m/git/NAT-TestServer [_/home/m/git/NAT-TestServer.test]
./server_test.go:18:5: dcBuffer redeclared in this block
        previous declaration at ./server.go:33:5
FAIL    _/home/m/git/NAT-TestServer [build failed]
```

**Comment by PascalPickel** [comment]
Fixed.

**Comment by coderbyheart** [comment]
Not really:

```
➜ go test
--- FAIL: TestTCP (0.00s)
    --- FAIL: TestTCP/TCP_Client#01 (0.00s)
        server_test.go:47: could not connect to server:  dial tcp :3051: connect: connection refused
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x566ce9]

goroutine 9 [running]:
testing.tRunner.func1.1(0x58fba0, 0x70e970)
        /usr/lib/go/src/testing/testing.go:941 +0x3d0
testing.tRunner.func1(0xc000126360)
        /usr/lib/go/src/testing/testing.go:944 +0x3f9
panic(0x58fba0, 0x70e970)
        /usr/lib/go/src/runtime/panic.go:967 +0x166
_/home/m/git/NAT-TestServer.TCPFunc(0xc000126360)
        /home/m/git/NAT-TestServer/server_test.go:49 +0x139
testing.tRunner(0xc000126360, 0x5ce788)
        /usr/lib/go/src/testing/testing.go:992 +0xdc
created by testing.(*T).Run
        /usr/lib/go/src/testing/testing.go:1043 +0x357
exit status 2
FAIL    _/home/m/git/NAT-TestServer     0.007s

```

**Comment by coderbyheart** [comment]
Please provide a README.md that shows how to test this.

**Comment by PascalPickel** [comment]
It's running without any errors for me. Not sure why this is happening. It's all running on localhost so there shouldn't be a routing or firewall issue I believe.

**Comment by PascalPickel** [comment]
Seems to be caused by running it in a linux environment. I'll look into it more.

**Comment by PascalPickel** [comment]
@coderbyheart Try again. It should be fixed now. Turns out I didn't guarantee the server had started before I ran the tests.

**Comment by coderbyheart** [comment]
Confirmed, not tests pass.
